[yorick]
# secrets are encrypted to this key, defaulting to the first ssh key
# I use a separate key because my ssh key is unusable by age
agekey = "age16t7splw64xc6qc7eannw2ahpxace763uu93sqr5d3l4uuy8hze0qcvu2j2"
sshkeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDo1N5E6qkb3McJOvv0PqI7E8iYLAcjil5RWc+zeTtN/ yorick"
]
# whitelisted in sshguard
allowed-ips = [
  "2a02:a464:5ed::/48" # home
]
# allow prod root access
production = true

[ayke]
sshkeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINbmv5LOl+qu5tKTaaUq49Jciv3S3hrI4hwVWBh7Spl6 ayke",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBWqwvAk43sLon1UtP/Swl2hRhetG1OmLCrfGp4tBr6V ayke@karpenoktem",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEkqGExf0OKNa+Fzq09JRYQjelMK3CjkqUiQEtrnZAry ayke@elstar-linux"
]
allowed-ips = []
production = true

[lars]
sshkeys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCbieYUtRGQ4nf4glQvrZDn72doP6W2uw2z9VqFq5sZLROXYa4jW8nwx4h+BiArGs+VPwn6lfsP19PX6yNIk74C/SkO26S1Zvbe7ffNusi6PH2BQIOWeAYKk+eZH+ZOeD8z07uDB7QffwRLwzSaPFg+zfRzsMFoXH/GE9qOQ4lnfk8czTZL7zbZf/yS7mDFztClXFciYsVwgRXNiFpfc+9mOkU0oBWtGo/WGUhB0Hds3a4ylyjjVAcC/l1H2bvc/Q3d6bbn23pUFl2V78Yg1B4b1MT34qbBV6whXAQd7KM9tND2ZhpF2XQ7Spi1QlOac0jup+sE+3bbvcjNqTI05DwJO/dX5F2gSAFkvSY4ZPqSX5ilE/hj4DQuhRgLmQdbVl5IFV9aLYqUvJcCqX9jRFMly4YTFXsFz18rGkxOYGZabcE1usBM2zRVDTtEP6Si5ii76Ocvp8aNFBB2Kf1whg8tziTv3kQEQ9fd2sRtE2J3xveJiwXjUBU2uikSOKe8JP47Tb6PYlv7Ty/6OI51aUQn++R72VNajdBJ1r1osp7leqTJ+sXuLlWLo/a7lDpDmgEI7dbxqmpjLcMce0JzqLKlP1Q2U/nkYy86xkjSTH1rNUI2JAbJx3iTcGy7bq12yfjNfcGAqY4GVXvisK1cpbF0RCjaFExwtmzorljHh6ZHjQ== lars"
]
allowed-ips = []
production = false

[dylan]
sshkeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINnv+Cj4rMYVbuK+Ww7fBAF4c8NccLa91emUNUKE8bAr"
]
allowed-ips = []
production = false
