#!/usr/bin/env python

import _import
import sys

from Mailman import Utils, MailList, UserDesc

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print 'Missing command'
		sys.exit(-1)
	cmd = sys.argv[1]
	if cmd == 'subscribe':
		if len(sys.argv) != 4:
			print 'Expected 3 parameters'
			sys.exit(-2)
		m = MailList.MailList(sys.argv[2])
		try:
			pw = Utils.MakeRandomPassword()
			desc = UserDesc.UserDesc(sys.argv[3], '', pw, False)
			m.ApprovedAddMember(desc, False, False)
			m.Save()
		finally:
			m.Unlock()
	elif cmd == 'unsubscribe':
		if len(sys.argv) != 4:
			print 'Expected 3 parameters'
			sys.exit(-3)
		m = MailList.MailList(sys.argv[2])
		try:
			m.ApprovedDeleteMember(sys.argv[3], admin_notif=False,
					userack=False)
			m.Save()
		finally:
			m.Unlock()
	else:
		print 'Unknown command'
		sys.exit(-4)
