#!/usr/bin/env python

import sys
import subprocess

if __name__ == '__main__':
	if len(sys.argv) < 2:
		print "Missing command"
		sys.exit(-1)
	cmd = sys.argv[1]
	if cmd == 'add-user':
		if len(sys.argv) != 3:
			print 'Expecting 2 arguments'
			sys.exit(-2)
		user = sys.argv[2]
		home = '/home/kn/%s' % user
		subprocess.call(['mkdir', home])
		subprocess.call(['useradd', '-d', home, '-g', 'kn', user])
		subprocess.call(['chown', '%s:kn' % user, home])
		subprocess.call(['chmod', '750', home])
	elif cmd == 'add-group':
		if len(sys.argv) != 3:
			print 'Expecting 2 arguments'
			sys.exit(-3)
		group = sys.argv[2]
		rawname = group.split('kn-')[1]
		home = '/groups/kn/%s' % rawname
		subprocess.call(['mkdir', home])
		subprocess.call(['groupadd', group])
		subprocess.call(['chown', 'root:%s' % group, home])
		subprocess.call(['chmod', '770', home])
	elif cmd == 'add-to':
		if len(sys.argv) != 4:
			print 'Expecting 3 arguments'
			sys.exit(-4)
		group = sys.argv[2]
		user = sys.argv[3]
		subprocess.call(['gpasswd', '-a', user, group])
	else:
		print 'Unknown command'
		sys.exit(-5)
	
