#!/usr/bin/env python
from __future__ import with_statement

import _import

import os
import sys
import MySQLdb

DOMAIN = 'karpenoktem.nl'

def read_ssv_file(filename):
	""" Reads values seperated by spaces in a simple one line file """
	with open(filename) as f:
		return f.readline()[:-1].split(' ')

if __name__ == '__main__':
	login = read_ssv_file('vpopmail.login')
	db = MySQLdb.connect(host='localhost', user=login[0],
			     passwd=login[2], db=login[1])
	
	if len(sys.argv) < 2:
		print "Missing action"
		sys.exit(-1)
	cmd = sys.argv[1]
	if cmd == 'add':
		if len(sys.argv) != 4:
			print "Expecting 3 arguments"
			sys.exit(-2)
		source = sys.argv[2]
		target = sys.argv[3]
		c = db.cursor()
		c.execute("INSERT INTO valias(`alias`, `valias_line`, `domain`) "+
			  "VALUES (%s, %s, %s)", (source, '&'+target, DOMAIN))
	elif cmd == 'alter':
		if len(sys.argv) != 4:
			print "Expecting 3 arguments"
			sys.exit(-3)
		source = sys.argv[2]
		target = sys.argv[3]
		c = db.cursor()
		c.execute("UPDATE valias SET `valias_line`=%s "+
			  "WHERE `domain`=%s and `alias`=%s", ('&'+target, DOMAIN, source))
	else:
		print "Unknown command"
		sys.exit(-4)
	
	

