# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hans.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hans.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nhans.proto\"\x12\n\x10GetMembershipReq\"\x89\x01\n\x11GetMembershipResp\x12\x36\n\nmembership\x18\x01 \x03(\x0b\x32\".GetMembershipResp.MembershipEntry\x1a<\n\x0fMembershipEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.ListInfo:\x02\x38\x01\"\xfc\x01\n\x0f\x41pplyChangesReq\x12\x1e\n\x06\x63reate\x18\x01 \x03(\x0b\x32\x0e.ListCreateReq\x12&\n\x03\x61\x64\x64\x18\x02 \x03(\x0b\x32\x19.ApplyChangesReq.AddEntry\x12,\n\x06remove\x18\x03 \x03(\x0b\x32\x1c.ApplyChangesReq.RemoveEntry\x1a\x37\n\x08\x41\x64\x64\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.MemberList:\x02\x38\x01\x1a:\n\x0bRemoveEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.MemberList:\x02\x38\x01\"\x12\n\x10\x41pplyChangesResp\"\x1a\n\x08ListInfo\x12\x0e\n\x06\x65mails\x18\x01 \x03(\t\"0\n\rListCreateReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\thumanName\x18\x02 \x01(\t\"\x1c\n\nMemberList\x12\x0e\n\x06\x65mails\x18\x01 \x03(\t2w\n\x04Hans\x12\x38\n\rGetMembership\x12\x11.GetMembershipReq\x1a\x12.GetMembershipResp\"\x00\x12\x35\n\x0c\x41pplyChanges\x12\x10.ApplyChangesReq\x1a\x11.ApplyChangesResp\"\x00\x62\x06proto3')
)




_GETMEMBERSHIPREQ = _descriptor.Descriptor(
  name='GetMembershipReq',
  full_name='GetMembershipReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=32,
)


_GETMEMBERSHIPRESP_MEMBERSHIPENTRY = _descriptor.Descriptor(
  name='MembershipEntry',
  full_name='GetMembershipResp.MembershipEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GetMembershipResp.MembershipEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='GetMembershipResp.MembershipEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=172,
)

_GETMEMBERSHIPRESP = _descriptor.Descriptor(
  name='GetMembershipResp',
  full_name='GetMembershipResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='membership', full_name='GetMembershipResp.membership', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETMEMBERSHIPRESP_MEMBERSHIPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=172,
)


_APPLYCHANGESREQ_ADDENTRY = _descriptor.Descriptor(
  name='AddEntry',
  full_name='ApplyChangesReq.AddEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ApplyChangesReq.AddEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ApplyChangesReq.AddEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=367,
)

_APPLYCHANGESREQ_REMOVEENTRY = _descriptor.Descriptor(
  name='RemoveEntry',
  full_name='ApplyChangesReq.RemoveEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ApplyChangesReq.RemoveEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ApplyChangesReq.RemoveEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=427,
)

_APPLYCHANGESREQ = _descriptor.Descriptor(
  name='ApplyChangesReq',
  full_name='ApplyChangesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='create', full_name='ApplyChangesReq.create', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='add', full_name='ApplyChangesReq.add', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remove', full_name='ApplyChangesReq.remove', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_APPLYCHANGESREQ_ADDENTRY, _APPLYCHANGESREQ_REMOVEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=427,
)


_APPLYCHANGESRESP = _descriptor.Descriptor(
  name='ApplyChangesResp',
  full_name='ApplyChangesResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=447,
)


_LISTINFO = _descriptor.Descriptor(
  name='ListInfo',
  full_name='ListInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emails', full_name='ListInfo.emails', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=475,
)


_LISTCREATEREQ = _descriptor.Descriptor(
  name='ListCreateReq',
  full_name='ListCreateReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ListCreateReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humanName', full_name='ListCreateReq.humanName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=525,
)


_MEMBERLIST = _descriptor.Descriptor(
  name='MemberList',
  full_name='MemberList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='emails', full_name='MemberList.emails', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=555,
)

_GETMEMBERSHIPRESP_MEMBERSHIPENTRY.fields_by_name['value'].message_type = _LISTINFO
_GETMEMBERSHIPRESP_MEMBERSHIPENTRY.containing_type = _GETMEMBERSHIPRESP
_GETMEMBERSHIPRESP.fields_by_name['membership'].message_type = _GETMEMBERSHIPRESP_MEMBERSHIPENTRY
_APPLYCHANGESREQ_ADDENTRY.fields_by_name['value'].message_type = _MEMBERLIST
_APPLYCHANGESREQ_ADDENTRY.containing_type = _APPLYCHANGESREQ
_APPLYCHANGESREQ_REMOVEENTRY.fields_by_name['value'].message_type = _MEMBERLIST
_APPLYCHANGESREQ_REMOVEENTRY.containing_type = _APPLYCHANGESREQ
_APPLYCHANGESREQ.fields_by_name['create'].message_type = _LISTCREATEREQ
_APPLYCHANGESREQ.fields_by_name['add'].message_type = _APPLYCHANGESREQ_ADDENTRY
_APPLYCHANGESREQ.fields_by_name['remove'].message_type = _APPLYCHANGESREQ_REMOVEENTRY
DESCRIPTOR.message_types_by_name['GetMembershipReq'] = _GETMEMBERSHIPREQ
DESCRIPTOR.message_types_by_name['GetMembershipResp'] = _GETMEMBERSHIPRESP
DESCRIPTOR.message_types_by_name['ApplyChangesReq'] = _APPLYCHANGESREQ
DESCRIPTOR.message_types_by_name['ApplyChangesResp'] = _APPLYCHANGESRESP
DESCRIPTOR.message_types_by_name['ListInfo'] = _LISTINFO
DESCRIPTOR.message_types_by_name['ListCreateReq'] = _LISTCREATEREQ
DESCRIPTOR.message_types_by_name['MemberList'] = _MEMBERLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMembershipReq = _reflection.GeneratedProtocolMessageType('GetMembershipReq', (_message.Message,), dict(
  DESCRIPTOR = _GETMEMBERSHIPREQ,
  __module__ = 'hans_pb2'
  # @@protoc_insertion_point(class_scope:GetMembershipReq)
  ))
_sym_db.RegisterMessage(GetMembershipReq)

GetMembershipResp = _reflection.GeneratedProtocolMessageType('GetMembershipResp', (_message.Message,), dict(

  MembershipEntry = _reflection.GeneratedProtocolMessageType('MembershipEntry', (_message.Message,), dict(
    DESCRIPTOR = _GETMEMBERSHIPRESP_MEMBERSHIPENTRY,
    __module__ = 'hans_pb2'
    # @@protoc_insertion_point(class_scope:GetMembershipResp.MembershipEntry)
    ))
  ,
  DESCRIPTOR = _GETMEMBERSHIPRESP,
  __module__ = 'hans_pb2'
  # @@protoc_insertion_point(class_scope:GetMembershipResp)
  ))
_sym_db.RegisterMessage(GetMembershipResp)
_sym_db.RegisterMessage(GetMembershipResp.MembershipEntry)

ApplyChangesReq = _reflection.GeneratedProtocolMessageType('ApplyChangesReq', (_message.Message,), dict(

  AddEntry = _reflection.GeneratedProtocolMessageType('AddEntry', (_message.Message,), dict(
    DESCRIPTOR = _APPLYCHANGESREQ_ADDENTRY,
    __module__ = 'hans_pb2'
    # @@protoc_insertion_point(class_scope:ApplyChangesReq.AddEntry)
    ))
  ,

  RemoveEntry = _reflection.GeneratedProtocolMessageType('RemoveEntry', (_message.Message,), dict(
    DESCRIPTOR = _APPLYCHANGESREQ_REMOVEENTRY,
    __module__ = 'hans_pb2'
    # @@protoc_insertion_point(class_scope:ApplyChangesReq.RemoveEntry)
    ))
  ,
  DESCRIPTOR = _APPLYCHANGESREQ,
  __module__ = 'hans_pb2'
  # @@protoc_insertion_point(class_scope:ApplyChangesReq)
  ))
_sym_db.RegisterMessage(ApplyChangesReq)
_sym_db.RegisterMessage(ApplyChangesReq.AddEntry)
_sym_db.RegisterMessage(ApplyChangesReq.RemoveEntry)

ApplyChangesResp = _reflection.GeneratedProtocolMessageType('ApplyChangesResp', (_message.Message,), dict(
  DESCRIPTOR = _APPLYCHANGESRESP,
  __module__ = 'hans_pb2'
  # @@protoc_insertion_point(class_scope:ApplyChangesResp)
  ))
_sym_db.RegisterMessage(ApplyChangesResp)

ListInfo = _reflection.GeneratedProtocolMessageType('ListInfo', (_message.Message,), dict(
  DESCRIPTOR = _LISTINFO,
  __module__ = 'hans_pb2'
  # @@protoc_insertion_point(class_scope:ListInfo)
  ))
_sym_db.RegisterMessage(ListInfo)

ListCreateReq = _reflection.GeneratedProtocolMessageType('ListCreateReq', (_message.Message,), dict(
  DESCRIPTOR = _LISTCREATEREQ,
  __module__ = 'hans_pb2'
  # @@protoc_insertion_point(class_scope:ListCreateReq)
  ))
_sym_db.RegisterMessage(ListCreateReq)

MemberList = _reflection.GeneratedProtocolMessageType('MemberList', (_message.Message,), dict(
  DESCRIPTOR = _MEMBERLIST,
  __module__ = 'hans_pb2'
  # @@protoc_insertion_point(class_scope:MemberList)
  ))
_sym_db.RegisterMessage(MemberList)


_GETMEMBERSHIPRESP_MEMBERSHIPENTRY._options = None
_APPLYCHANGESREQ_ADDENTRY._options = None
_APPLYCHANGESREQ_REMOVEENTRY._options = None

_HANS = _descriptor.ServiceDescriptor(
  name='Hans',
  full_name='Hans',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=557,
  serialized_end=676,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMembership',
    full_name='Hans.GetMembership',
    index=0,
    containing_service=None,
    input_type=_GETMEMBERSHIPREQ,
    output_type=_GETMEMBERSHIPRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ApplyChanges',
    full_name='Hans.ApplyChanges',
    index=1,
    containing_service=None,
    input_type=_APPLYCHANGESREQ,
    output_type=_APPLYCHANGESRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HANS)

DESCRIPTOR.services_by_name['Hans'] = _HANS

# @@protoc_insertion_point(module_scope)
