from django.conf.urls.defaults import *

from kn.leden import views

urlpatterns = patterns('',
	url(r'^gebruikers/(?:p/(?P<page>[0-9]+)/)?$',
	    views.user_list, name='user-list'),
	url(r'^naamdrager/(?P<name>[^/]+)/$',
	    views.entity_detail, name='entity-by-name'),
	url(r'^id/(?P<_id>[^/]+)/$',
	    views.entity_detail, name='entity-by-id'),
	url(r'^gebruiker/(?P<name>[^/]+)/$',
	    views.entity_detail, {'type': 'user'}, name='user-by-name'),
	url(r'^gebruiker/id/(?P<_id>[^/]+)/$',
	    views.entity_detail, {'type': 'user'}, name='user-by-id'),
	url(r'^groep/(?P<name>[^/]+)/$',
	    views.entity_detail, {'type': 'group'}, name='group-by-name'),
	url(r'^groep/id/(?P<_id>[^/]+)/$',
	    views.entity_detail, {'type': 'group'}, name='group-by-id'),
	url(r'^zetel/(?P<name>[^/]+)/$',
	    views.entity_detail, {'type': 'seat'}, name='seat-by-name'),
	url(r'^zetel/id/(?P<_id>[^/]+)/$',
	    views.entity_detail, {'type': 'seat'}, name='seat-by-id'),
	url(r'^stempel/(?P<name>[^/]+)/$',
	    views.entity_detail, {'type': 'tag'}, name='tag-by-name'),
	url(r'^stempel/id/(?P<_id>[^/]+)/$',
	    views.entity_detail, {'type': 'tag'}, name='tag-by-id'),
	url(r'^studie/(?P<name>[^/]+)/$',
	    views.entity_detail, {'type': 'tag'}, name='study-by-name'),
	url(r'^studie/id/(?P<_id>[^/]+)/$',
	    views.entity_detail, {'type': 'study'}, name='study-by-id'),
	url(r'^instituut/(?P<name>[^/]+)/$',
	    views.entity_detail, {'type': 'institute'},
	    name='institute-by-name'),
	url(r'^instituut/id/(?P<_id>[^/]+)/$',
	    views.entity_detail, {'type': 'institute'},
	    name='institute-by-id'),
	url(r'^smoel/(?P<name>[^.]+).jpg$',
	    views.user_smoel, name='user-smoel'),
	url(r'^ik/wachtwoord$', views.ik_chpasswd, name="chpasswd"),
)

