# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protobufs.messages import common_pb2 as protobufs_dot_messages_dot_common__pb2
from protobufs.messages import daan_pb2 as protobufs_dot_messages_dot_daan__pb2


class DaanStub(object):
  """Daan is the root daemon.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetPostfixMap = channel.unary_unary(
        '/Daan/SetPostfixMap',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.PostfixMap.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.SetPostfixSenderLoginMap = channel.unary_unary(
        '/Daan/SetPostfixSenderLoginMap',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.PostfixMap.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.ApplyWikiChanges = channel.unary_unary(
        '/Daan/ApplyWikiChanges',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.WikiChanges.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.ApplyLDAPChanges = channel.unary_unary(
        '/Daan/ApplyLDAPChanges',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.LDAPChanges.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.SetLDAPPassword = channel.unary_unary(
        '/Daan/SetLDAPPassword',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.LDAPNewPassword.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.FotoadminCreateEvent = channel.unary_unary(
        '/Daan/FotoadminCreateEvent',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.FotoadminEvent.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.FotoadminMoveFotos = channel.unary_unary(
        '/Daan/FotoadminMoveFotos',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.FotoadminMoveAction.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )


class DaanServicer(object):
  """Daan is the root daemon.
  """

  def SetPostfixMap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPostfixSenderLoginMap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ApplyWikiChanges(self, request, context):
    """Apply changes to synced wiki users previously thought up by giedo.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ApplyLDAPChanges(self, request, context):
    """Apply changes to the LDAP database previously thought up by giedo.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLDAPPassword(self, request, context):
    """Set the LDAP password.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FotoadminCreateEvent(self, request, context):
    """Create a new event in the photo album.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FotoadminMoveFotos(self, request, context):
    """Move a user photo directory into the photo album created above.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DaanServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetPostfixMap': grpc.unary_unary_rpc_method_handler(
          servicer.SetPostfixMap,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.PostfixMap.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'SetPostfixSenderLoginMap': grpc.unary_unary_rpc_method_handler(
          servicer.SetPostfixSenderLoginMap,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.PostfixMap.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'ApplyWikiChanges': grpc.unary_unary_rpc_method_handler(
          servicer.ApplyWikiChanges,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.WikiChanges.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'ApplyLDAPChanges': grpc.unary_unary_rpc_method_handler(
          servicer.ApplyLDAPChanges,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.LDAPChanges.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'SetLDAPPassword': grpc.unary_unary_rpc_method_handler(
          servicer.SetLDAPPassword,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.LDAPNewPassword.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'FotoadminCreateEvent': grpc.unary_unary_rpc_method_handler(
          servicer.FotoadminCreateEvent,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.FotoadminEvent.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'FotoadminMoveFotos': grpc.unary_unary_rpc_method_handler(
          servicer.FotoadminMoveFotos,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.FotoadminMoveAction.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Daan', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
