# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/messages/daan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobufs.messages import common_pb2 as protobufs_dot_messages_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotobufs/messages/daan.proto\x1a\x1fprotobufs/messages/common.proto\"e\n\nPostfixMap\x12!\n\x03map\x18\x01 \x03(\x0b\x32\x14.PostfixMap.MapEntry\x1a\x34\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.Strings:\x02\x38\x01\"\x19\n\x07Strings\x12\x0e\n\x06values\x18\x01 \x03(\t2a\n\x04\x44\x61\x61n\x12&\n\rSetPostfixMap\x12\x0b.PostfixMap\x1a\x06.Empty\"\x00\x12\x31\n\x18SetPostfixSenderLoginMap\x12\x0b.PostfixMap\x1a\x06.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.messages.daan_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTFIXMAP_MAPENTRY._options = None
  _POSTFIXMAP_MAPENTRY._serialized_options = b'8\001'
  _POSTFIXMAP._serialized_start=66
  _POSTFIXMAP._serialized_end=167
  _POSTFIXMAP_MAPENTRY._serialized_start=115
  _POSTFIXMAP_MAPENTRY._serialized_end=167
  _STRINGS._serialized_start=169
  _STRINGS._serialized_end=194
  _DAAN._serialized_start=196
  _DAAN._serialized_end=293
# @@protoc_insertion_point(module_scope)
