# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobufs.messages import common_pb2 as protobufs_dot_messages_dot_common__pb2
from protobufs.messages import daan_pb2 as protobufs_dot_messages_dot_daan__pb2


class DaanStub(object):
    """Daan is the root daemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPostfixMap = channel.unary_unary(
                '/Daan/SetPostfixMap',
                request_serializer=protobufs_dot_messages_dot_daan__pb2.PostfixMap.SerializeToString,
                response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
                )
        self.SetPostfixSenderLoginMap = channel.unary_unary(
                '/Daan/SetPostfixSenderLoginMap',
                request_serializer=protobufs_dot_messages_dot_daan__pb2.PostfixMap.SerializeToString,
                response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
                )
        self.FotoadminCreateEvent = channel.unary_unary(
                '/Daan/FotoadminCreateEvent',
                request_serializer=protobufs_dot_messages_dot_daan__pb2.FotoadminEvent.SerializeToString,
                response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
                )


class DaanServicer(object):
    """Daan is the root daemon.
    """

    def SetPostfixMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPostfixSenderLoginMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FotoadminCreateEvent(self, request, context):
        """Create a new event in the photo album.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaanServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPostfixMap': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPostfixMap,
                    request_deserializer=protobufs_dot_messages_dot_daan__pb2.PostfixMap.FromString,
                    response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
            ),
            'SetPostfixSenderLoginMap': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPostfixSenderLoginMap,
                    request_deserializer=protobufs_dot_messages_dot_daan__pb2.PostfixMap.FromString,
                    response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
            ),
            'FotoadminCreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.FotoadminCreateEvent,
                    request_deserializer=protobufs_dot_messages_dot_daan__pb2.FotoadminEvent.FromString,
                    response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Daan', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Daan(object):
    """Daan is the root daemon.
    """

    @staticmethod
    def SetPostfixMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Daan/SetPostfixMap',
            protobufs_dot_messages_dot_daan__pb2.PostfixMap.SerializeToString,
            protobufs_dot_messages_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPostfixSenderLoginMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Daan/SetPostfixSenderLoginMap',
            protobufs_dot_messages_dot_daan__pb2.PostfixMap.SerializeToString,
            protobufs_dot_messages_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FotoadminCreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Daan/FotoadminCreateEvent',
            protobufs_dot_messages_dot_daan__pb2.FotoadminEvent.SerializeToString,
            protobufs_dot_messages_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
