# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protobufs.messages import common_pb2 as protobufs_dot_messages_dot_common__pb2
from protobufs.messages import daan_pb2 as protobufs_dot_messages_dot_daan__pb2
from protobufs.messages import giedo_pb2 as protobufs_dot_messages_dot_giedo__pb2
from protobufs.messages import moniek_pb2 as protobufs_dot_messages_dot_moniek__pb2


class GiedoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SyncAsync = channel.unary_unary(
        '/Giedo/SyncAsync',
        request_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.SyncBlocking = channel.unary_unary(
        '/Giedo/SyncBlocking',
        request_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.LastSynced = channel.unary_unary(
        '/Giedo/LastSynced',
        request_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_giedo__pb2.LastSyncedResult.FromString,
        )
    self.SetPassword = channel.unary_unary(
        '/Giedo/SetPassword',
        request_serializer=protobufs_dot_messages_dot_giedo__pb2.GiedoSetPassword.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.FotoadminScanUserdirs = channel.unary_unary(
        '/Giedo/FotoadminScanUserdirs',
        request_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_giedo__pb2.FotoadminUserdirs.FromString,
        )
    self.FotoadminCreateEvent = channel.unary_unary(
        '/Giedo/FotoadminCreateEvent',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.FotoadminEvent.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.FotoadminMoveFotos = channel.unary_unary(
        '/Giedo/FotoadminMoveFotos',
        request_serializer=protobufs_dot_messages_dot_daan__pb2.FotoadminMoveAction.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.ScanFotos = channel.unary_unary(
        '/Giedo/ScanFotos',
        request_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.UpdateSiteAgenda = channel.unary_unary(
        '/Giedo/UpdateSiteAgenda',
        request_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
        )
    self.FinGetAccount = channel.unary_unary(
        '/Giedo/FinGetAccount',
        request_serializer=protobufs_dot_messages_dot_moniek__pb2.FinGetAccountReq.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinGetAccountResp.FromString,
        )
    self.FinGetDebitors = channel.unary_unary(
        '/Giedo/FinGetDebitors',
        request_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinDebitors.FromString,
        )
    self.FinCheckNames = channel.unary_unary(
        '/Giedo/FinCheckNames',
        request_serializer=protobufs_dot_messages_dot_moniek__pb2.FinNamesList.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinMissingNames.FromString,
        )
    self.FinGetGnuCashObject = channel.unary_unary(
        '/Giedo/FinGetGnuCashObject',
        request_serializer=protobufs_dot_messages_dot_moniek__pb2.FinObjectRequest.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinObject.FromString,
        )
    self.FinGetYears = channel.unary_unary(
        '/Giedo/FinGetYears',
        request_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinYears.FromString,
        )
    self.FinGetErrors = channel.unary_unary(
        '/Giedo/FinGetErrors',
        request_serializer=protobufs_dot_messages_dot_moniek__pb2.FinYear.SerializeToString,
        response_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinErrors.FromString,
        )


class GiedoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SyncAsync(self, request, context):
    """SyncAsync starts a synchronization action in the background.
    All external services will be updated with the information in the web
    application database, by adding/removing users, adding/removing group
    memberships, etc.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SyncBlocking(self, request, context):
    """SyncBlocking is the blocking version of SyncAsync.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LastSynced(self, request, context):
    """LastSynced returns the time when the last synchronization was completed.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPassword(self, request, context):
    """SetPassword updates the password of this user throughout the system.
    It either succeeds or returns an error with code INVALID_ARGUMENT if the
    user is not found or the old password doesn't match.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FotoadminScanUserdirs(self, request, context):
    """FotoadminScanUserdirs returns a list of directories containing photo
    albums uploaded by users that can be moved into the KN photo album.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FotoadminCreateEvent(self, request, context):
    """Create a new event in the photo album.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FotoadminMoveFotos(self, request, context):
    """FotoadminMoveFotos moves photos from the location in the user directory
    (unix, wolk), to an event in the photo book. The photos are removed from
    the user directory afterwards.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ScanFotos(self, request, context):
    """ScanFotos runs a (blocking) scan to index all photos in the photo book.
    New photos are added and old photos are marked lost.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSiteAgenda(self, request, context):
    """UpdateSiteAgenda fetches the current agenda from Google Calendar and
    updates the cached agenda on the website with it.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinGetAccount(self, request, context):
    """FinGetAccount returns the balance sheet for one account, including all
    transactions.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinGetDebitors(self, request, context):
    """FinGetDebitors returns a list of users that are in depth. This is used
    for sending reminder messages, for example.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinCheckNames(self, request, context):
    """FinCheckNames checks whether the names (users, committees) in the website
    match up with what is in the financial administration. It returns a list
    of missing names on both sides.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinGetGnuCashObject(self, request, context):
    """FinGetGnuCashObject returns an opaque blob that contains a
    msgpack-serialized buffer of the GnuCash object(s) with the given path.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinGetYears(self, request, context):
    """FinGetYears returns a map where the keys are the currently tracked years
    and the values are the YAML files that contain the cached data for those
    years.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinGetErrors(self, request, context):
    """FinGetErrors returns a list of errors and other questionable things in
    the financial administration of the given year.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GiedoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SyncAsync': grpc.unary_unary_rpc_method_handler(
          servicer.SyncAsync,
          request_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'SyncBlocking': grpc.unary_unary_rpc_method_handler(
          servicer.SyncBlocking,
          request_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'LastSynced': grpc.unary_unary_rpc_method_handler(
          servicer.LastSynced,
          request_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
          response_serializer=protobufs_dot_messages_dot_giedo__pb2.LastSyncedResult.SerializeToString,
      ),
      'SetPassword': grpc.unary_unary_rpc_method_handler(
          servicer.SetPassword,
          request_deserializer=protobufs_dot_messages_dot_giedo__pb2.GiedoSetPassword.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'FotoadminScanUserdirs': grpc.unary_unary_rpc_method_handler(
          servicer.FotoadminScanUserdirs,
          request_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
          response_serializer=protobufs_dot_messages_dot_giedo__pb2.FotoadminUserdirs.SerializeToString,
      ),
      'FotoadminCreateEvent': grpc.unary_unary_rpc_method_handler(
          servicer.FotoadminCreateEvent,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.FotoadminEvent.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'FotoadminMoveFotos': grpc.unary_unary_rpc_method_handler(
          servicer.FotoadminMoveFotos,
          request_deserializer=protobufs_dot_messages_dot_daan__pb2.FotoadminMoveAction.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'ScanFotos': grpc.unary_unary_rpc_method_handler(
          servicer.ScanFotos,
          request_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'UpdateSiteAgenda': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSiteAgenda,
          request_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
          response_serializer=protobufs_dot_messages_dot_common__pb2.Empty.SerializeToString,
      ),
      'FinGetAccount': grpc.unary_unary_rpc_method_handler(
          servicer.FinGetAccount,
          request_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinGetAccountReq.FromString,
          response_serializer=protobufs_dot_messages_dot_moniek__pb2.FinGetAccountResp.SerializeToString,
      ),
      'FinGetDebitors': grpc.unary_unary_rpc_method_handler(
          servicer.FinGetDebitors,
          request_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
          response_serializer=protobufs_dot_messages_dot_moniek__pb2.FinDebitors.SerializeToString,
      ),
      'FinCheckNames': grpc.unary_unary_rpc_method_handler(
          servicer.FinCheckNames,
          request_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinNamesList.FromString,
          response_serializer=protobufs_dot_messages_dot_moniek__pb2.FinMissingNames.SerializeToString,
      ),
      'FinGetGnuCashObject': grpc.unary_unary_rpc_method_handler(
          servicer.FinGetGnuCashObject,
          request_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinObjectRequest.FromString,
          response_serializer=protobufs_dot_messages_dot_moniek__pb2.FinObject.SerializeToString,
      ),
      'FinGetYears': grpc.unary_unary_rpc_method_handler(
          servicer.FinGetYears,
          request_deserializer=protobufs_dot_messages_dot_common__pb2.Empty.FromString,
          response_serializer=protobufs_dot_messages_dot_moniek__pb2.FinYears.SerializeToString,
      ),
      'FinGetErrors': grpc.unary_unary_rpc_method_handler(
          servicer.FinGetErrors,
          request_deserializer=protobufs_dot_messages_dot_moniek__pb2.FinYear.FromString,
          response_serializer=protobufs_dot_messages_dot_moniek__pb2.FinErrors.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Giedo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
