# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/messages/giedo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobufs.messages import common_pb2 as protobufs_dot_messages_dot_common__pb2
from protobufs.messages import daan_pb2 as protobufs_dot_messages_dot_daan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/messages/giedo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1eprotobufs/messages/giedo.proto\x1a\x1fprotobufs/messages/common.proto\x1a\x1dprotobufs/messages/daan.proto\"B\n\x10GiedoSetPassword\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07oldpass\x18\x02 \x01(\t\x12\x0f\n\x07newpass\x18\x03 \x01(\t\" \n\x10LastSyncedResult\x12\x0c\n\x04time\x18\x01 \x01(\x01\x32\x97\x02\n\x05Giedo\x12\x1d\n\tSyncAsync\x12\x06.Empty\x1a\x06.Empty\"\x00\x12 \n\x0cSyncBlocking\x12\x06.Empty\x1a\x06.Empty\"\x00\x12)\n\nLastSynced\x12\x06.Empty\x1a\x11.LastSyncedResult\"\x00\x12*\n\x0bSetPassword\x12\x11.GiedoSetPassword\x1a\x06.Empty\"\x00\x12\x31\n\x14\x46otoadminCreateEvent\x12\x0f.FotoadminEvent\x1a\x06.Empty\"\x00\x12\x1d\n\tScanFotos\x12\x06.Empty\x1a\x06.Empty\"\x00\x12$\n\x10UpdateSiteAgenda\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[protobufs_dot_messages_dot_common__pb2.DESCRIPTOR,protobufs_dot_messages_dot_daan__pb2.DESCRIPTOR,])




_GIEDOSETPASSWORD = _descriptor.Descriptor(
  name='GiedoSetPassword',
  full_name='GiedoSetPassword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='GiedoSetPassword.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oldpass', full_name='GiedoSetPassword.oldpass', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newpass', full_name='GiedoSetPassword.newpass', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=164,
)


_LASTSYNCEDRESULT = _descriptor.Descriptor(
  name='LastSyncedResult',
  full_name='LastSyncedResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='LastSyncedResult.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['GiedoSetPassword'] = _GIEDOSETPASSWORD
DESCRIPTOR.message_types_by_name['LastSyncedResult'] = _LASTSYNCEDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GiedoSetPassword = _reflection.GeneratedProtocolMessageType('GiedoSetPassword', (_message.Message,), {
  'DESCRIPTOR' : _GIEDOSETPASSWORD,
  '__module__' : 'protobufs.messages.giedo_pb2'
  # @@protoc_insertion_point(class_scope:GiedoSetPassword)
  })
_sym_db.RegisterMessage(GiedoSetPassword)

LastSyncedResult = _reflection.GeneratedProtocolMessageType('LastSyncedResult', (_message.Message,), {
  'DESCRIPTOR' : _LASTSYNCEDRESULT,
  '__module__' : 'protobufs.messages.giedo_pb2'
  # @@protoc_insertion_point(class_scope:LastSyncedResult)
  })
_sym_db.RegisterMessage(LastSyncedResult)



_GIEDO = _descriptor.ServiceDescriptor(
  name='Giedo',
  full_name='Giedo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=201,
  serialized_end=480,
  methods=[
  _descriptor.MethodDescriptor(
    name='SyncAsync',
    full_name='Giedo.SyncAsync',
    index=0,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SyncBlocking',
    full_name='Giedo.SyncBlocking',
    index=1,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LastSynced',
    full_name='Giedo.LastSynced',
    index=2,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=_LASTSYNCEDRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetPassword',
    full_name='Giedo.SetPassword',
    index=3,
    containing_service=None,
    input_type=_GIEDOSETPASSWORD,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FotoadminCreateEvent',
    full_name='Giedo.FotoadminCreateEvent',
    index=4,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_daan__pb2._FOTOADMINEVENT,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ScanFotos',
    full_name='Giedo.ScanFotos',
    index=5,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateSiteAgenda',
    full_name='Giedo.UpdateSiteAgenda',
    index=6,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GIEDO)

DESCRIPTOR.services_by_name['Giedo'] = _GIEDO

# @@protoc_insertion_point(module_scope)
