# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/messages/giedo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobufs.messages import common_pb2 as protobufs_dot_messages_dot_common__pb2
from protobufs.messages import daan_pb2 as protobufs_dot_messages_dot_daan__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/messages/giedo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1eprotobufs/messages/giedo.proto\x1a\x1fprotobufs/messages/common.proto\x1a\x1dprotobufs/messages/daan.proto\"B\n\x10GiedoSetPassword\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07oldpass\x18\x02 \x01(\t\x12\x0f\n\x07newpass\x18\x03 \x01(\t\"8\n\x11\x46otoadminUserdirs\x12#\n\x08userdirs\x18\x01 \x03(\x0b\x32\x11.FotoadminUserdir\"5\n\x10\x46otoadminUserdir\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x13\n\x0b\x64isplayName\x18\x02 \x01(\t\" \n\x10LastSyncedResult\x12\x0c\n\x04time\x18\x01 \x01(\x01\x32\x84\x03\n\x05Giedo\x12\x1d\n\tSyncAsync\x12\x06.Empty\x1a\x06.Empty\"\x00\x12 \n\x0cSyncBlocking\x12\x06.Empty\x1a\x06.Empty\"\x00\x12)\n\nLastSynced\x12\x06.Empty\x1a\x11.LastSyncedResult\"\x00\x12*\n\x0bSetPassword\x12\x11.GiedoSetPassword\x1a\x06.Empty\"\x00\x12\x35\n\x15\x46otoadminScanUserdirs\x12\x06.Empty\x1a\x12.FotoadminUserdirs\"\x00\x12\x31\n\x14\x46otoadminCreateEvent\x12\x0f.FotoadminEvent\x1a\x06.Empty\"\x00\x12\x34\n\x12\x46otoadminMoveFotos\x12\x14.FotoadminMoveAction\x1a\x06.Empty\"\x00\x12\x1d\n\tScanFotos\x12\x06.Empty\x1a\x06.Empty\"\x00\x12$\n\x10UpdateSiteAgenda\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[protobufs_dot_messages_dot_common__pb2.DESCRIPTOR,protobufs_dot_messages_dot_daan__pb2.DESCRIPTOR,])




_GIEDOSETPASSWORD = _descriptor.Descriptor(
  name='GiedoSetPassword',
  full_name='GiedoSetPassword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='GiedoSetPassword.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oldpass', full_name='GiedoSetPassword.oldpass', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newpass', full_name='GiedoSetPassword.newpass', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=164,
)


_FOTOADMINUSERDIRS = _descriptor.Descriptor(
  name='FotoadminUserdirs',
  full_name='FotoadminUserdirs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userdirs', full_name='FotoadminUserdirs.userdirs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=222,
)


_FOTOADMINUSERDIR = _descriptor.Descriptor(
  name='FotoadminUserdir',
  full_name='FotoadminUserdir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='FotoadminUserdir.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='FotoadminUserdir.displayName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=277,
)


_LASTSYNCEDRESULT = _descriptor.Descriptor(
  name='LastSyncedResult',
  full_name='LastSyncedResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='LastSyncedResult.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=311,
)

_FOTOADMINUSERDIRS.fields_by_name['userdirs'].message_type = _FOTOADMINUSERDIR
DESCRIPTOR.message_types_by_name['GiedoSetPassword'] = _GIEDOSETPASSWORD
DESCRIPTOR.message_types_by_name['FotoadminUserdirs'] = _FOTOADMINUSERDIRS
DESCRIPTOR.message_types_by_name['FotoadminUserdir'] = _FOTOADMINUSERDIR
DESCRIPTOR.message_types_by_name['LastSyncedResult'] = _LASTSYNCEDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GiedoSetPassword = _reflection.GeneratedProtocolMessageType('GiedoSetPassword', (_message.Message,), dict(
  DESCRIPTOR = _GIEDOSETPASSWORD,
  __module__ = 'protobufs.messages.giedo_pb2'
  # @@protoc_insertion_point(class_scope:GiedoSetPassword)
  ))
_sym_db.RegisterMessage(GiedoSetPassword)

FotoadminUserdirs = _reflection.GeneratedProtocolMessageType('FotoadminUserdirs', (_message.Message,), dict(
  DESCRIPTOR = _FOTOADMINUSERDIRS,
  __module__ = 'protobufs.messages.giedo_pb2'
  # @@protoc_insertion_point(class_scope:FotoadminUserdirs)
  ))
_sym_db.RegisterMessage(FotoadminUserdirs)

FotoadminUserdir = _reflection.GeneratedProtocolMessageType('FotoadminUserdir', (_message.Message,), dict(
  DESCRIPTOR = _FOTOADMINUSERDIR,
  __module__ = 'protobufs.messages.giedo_pb2'
  # @@protoc_insertion_point(class_scope:FotoadminUserdir)
  ))
_sym_db.RegisterMessage(FotoadminUserdir)

LastSyncedResult = _reflection.GeneratedProtocolMessageType('LastSyncedResult', (_message.Message,), dict(
  DESCRIPTOR = _LASTSYNCEDRESULT,
  __module__ = 'protobufs.messages.giedo_pb2'
  # @@protoc_insertion_point(class_scope:LastSyncedResult)
  ))
_sym_db.RegisterMessage(LastSyncedResult)



_GIEDO = _descriptor.ServiceDescriptor(
  name='Giedo',
  full_name='Giedo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=314,
  serialized_end=702,
  methods=[
  _descriptor.MethodDescriptor(
    name='SyncAsync',
    full_name='Giedo.SyncAsync',
    index=0,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SyncBlocking',
    full_name='Giedo.SyncBlocking',
    index=1,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LastSynced',
    full_name='Giedo.LastSynced',
    index=2,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=_LASTSYNCEDRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetPassword',
    full_name='Giedo.SetPassword',
    index=3,
    containing_service=None,
    input_type=_GIEDOSETPASSWORD,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FotoadminScanUserdirs',
    full_name='Giedo.FotoadminScanUserdirs',
    index=4,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=_FOTOADMINUSERDIRS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FotoadminCreateEvent',
    full_name='Giedo.FotoadminCreateEvent',
    index=5,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_daan__pb2._FOTOADMINEVENT,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FotoadminMoveFotos',
    full_name='Giedo.FotoadminMoveFotos',
    index=6,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_daan__pb2._FOTOADMINMOVEACTION,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ScanFotos',
    full_name='Giedo.ScanFotos',
    index=7,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateSiteAgenda',
    full_name='Giedo.UpdateSiteAgenda',
    index=8,
    containing_service=None,
    input_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    output_type=protobufs_dot_messages_dot_common__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GIEDO)

DESCRIPTOR.services_by_name['Giedo'] = _GIEDO

# @@protoc_insertion_point(module_scope)
