import os.path

from django.conf.urls.defaults import *
from django.conf import settings
import django.views.generic as generic
import django.views.generic.simple
from kn.base.views import direct_to_folder

urlpatterns = patterns('',
    url(r'^(?:(?:home|default)/?)?$', generic.simple.direct_to_template,
            {'template': 'static/home.html'}, name='home'),
    url(r'^(?:over|watis)/?$',
        generic.simple.direct_to_template,
            {'template': 'static/over.html'}, name='over'),
    url(r'^contact/?$', generic.simple.direct_to_template,
            {'template': 'static/contact.html'}, name='contact'),
    url(r'^agenda/?$', generic.simple.direct_to_template,
            {'template': 'static/agenda.html'}, name='agenda'),
    url(r'^lidworden/?$', generic.simple.direct_to_template,
            {'template': 'static/lidworden.html'}, name='lidworden'),
    url(r'^geschiedenis/?$', generic.simple.direct_to_template,
            {'template': 'static/geschiedenis.html'}, name='geschiedenis'),
    url(r'^activiteiten/?$', generic.simple.direct_to_template,
            {'template': 'static/activiteiten.html'}, name='activiteiten'),
    url(r'^(?:akta|an|aktanokturna)/?$', generic.simple.direct_to_template,
            {'template': 'static/aktanokturna.html'}, name='aktanokturna'),
    url(r'^zusjes/?$', generic.simple.direct_to_template,
            {'template': 'static/zusjes.html'}, name='zusjes'),
    url(r'^route/?$', generic.simple.direct_to_template,
            {'template': 'static/route.html'}, name='route'),
    url(r'^merchandise/?$', generic.simple.direct_to_template,
            {'template': 'static/merchandise.html'}, name='merchandise'),
    url(r'^sponsoren/?$', generic.simple.direct_to_template,
            {'template': 'static/sponsoren.html'}, name='sponsoren'),
    url(r'^media/?$', generic.simple.direct_to_template,
            {'template': 'static/media.html'}, name='media'),
    url(r'^links/?$', generic.simple.direct_to_template,
            {'template': 'static/links.html'}, name='links'),
    url(r'^robots.txt/?$', generic.simple.direct_to_template,
            {'template': 'static/robots.txt',
             'mimetype': 'text/plain'}),

    url(r'^bestuur4/?$', generic.simple.direct_to_template,
            {'template': 'static/bestuur4.html'}, name='bestuur4'),
    url(r'^bestuur5/?$', generic.simple.direct_to_template,
            {'template': 'static/bestuur5.html'}, name='bestuur5'),
    url(r'^bestuur6/?$', generic.simple.direct_to_template,
            {'template': 'static/bestuur6.html'}, name='bestuur6'),
    url(r'^bestuur7/?$', generic.simple.direct_to_template,
            {'template': 'static/bestuur7.html'}, name='bestuur7'),
    url(r'^bestuur8/?$', generic.simple.direct_to_template,
            {'template': 'static/bestuur8.html'}, name='bestuur8'),
    url(r'^bestuur9/?$', generic.simple.direct_to_template,
            {'template': 'static/bestuur9.html'}, name='bestuur9'),
    url(r'^bestuur10/?$', generic.simple.direct_to_template,
            {'template': 'static/bestuur10.html'}, name='bestuur10'),

    url(r'^introPoster2013/?$', generic.simple.direct_to_template,
            {'template': 'static/introPoster2013.html'},
            name='introPoster2013'),
    url(r'^introPoster2012/?$', generic.simple.direct_to_template,
            {'template': 'static/introPoster2012.html'},
            name='introPoster2012'),
    url(r'^introPoster2011/?$', generic.simple.direct_to_template,
            {'template': 'static/introPoster2011.html'},
            name='introPoster2011'),
    url(r'^introPoster2010/?$', generic.simple.direct_to_template,
            {'template': 'static/introPoster2010.html'},
            name='introPoster2010'),
    url(r'^introPoster2009/?$', generic.simple.direct_to_template,
            {'template': 'static/introPoster2009.html'},
            name='introPoster2009'),
    url(r'^lustrumPoster/?$', generic.simple.direct_to_template,
            {'template': 'static/lustrumPoster.html'},
            name='lustrumPoster'),

    url(r'^lustrum/?$', generic.simple.direct_to_template,
            {'template': 'static/lustrum.html'},
            name='lustrum'),
    url(r'^intro2008/?$', generic.simple.direct_to_template,
            {'template': 'static/intro2008.html'},
            name='intro2008'),
    url(r'^intro2009/?$', generic.simple.direct_to_template,
            {'template': 'static/intro2009.html'},
            name='intro2009'),
    url(r'^intro2010/?$', generic.simple.direct_to_template,
            {'template': 'static/intro2010.html'},
            name='intro2010'),

    # Forwards
    # TODO make configurable for khandhas
    url(r'^hink-stap/fotos-pdn/?$', generic.simple.redirect_to,
            {'url': '/fotos/index.php?album=pdn'},
            name='fotos-pdn'),
    url(r'^hink-stap/fotos/?$', generic.simple.redirect_to,
            {'url': '/fotos'},
            name='fotos'),
    url(r'^hink-stap/stukken/?$', generic.simple.redirect_to,
            {'url': '/groups/leden'},
            name='stukken'),
    url(r'^hink-stap/wiki/?$', generic.simple.redirect_to,
            {'url': '/wiki'},
            name='wiki'),
    url(r'^hink-stap/forum/?$', generic.simple.redirect_to,
            {'url': '/forum'},
            name='forum'),

    # Backwards compatibility
    url(r'^img/(?P<subdir>.*)', direct_to_folder,
            {'root': os.path.join(settings.MEDIA_ROOT, 'static/img') }),
)

# vim: et:sta:bs=2:sw=4:
